/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import restaurante.*;

/**
 *
 * @author HP
 */
public class IUPrincipal extends javax.swing.JFrame {

    Empleado ep;
    Menus me;
  
    
    public IUPrincipal() {
        initComponents();
    }
    public IUPrincipal(Empleado ep){
        initComponents();
        this.setLocationRelativeTo(null);
        this.ep=ep;
        
        
        labUsuario.setText(ep.getCargo());
        labNombre.setText(ep.getNombre());
        
        if(ep.getCargo().equals("Administrador")){
            
        }else if(ep.getCargo().equals("Mesero")){
            cajaMenu.setVisible(false);
            cocinaMenu.setVisible(false);
            insertarDatos.setVisible(false);
            reporteMenu.setVisible(false);
        }else if(ep.getCargo().equals("Cajero")){
            atencionMenu.setVisible(false);
            mesasMenu.setVisible(false);
            cocinaMenu.setVisible(false);
            insertarDatos.setVisible(false);
            reporteMenu.setVisible(false);
        }else if(ep.getCargo().equals("Chef")){
            atencionMenu.setVisible(false);
            mesasMenu.setVisible(false);
            cajaMenu.setVisible(false);
            insertarDatos.setVisible(false);
            reporteMenu.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        labUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        atencionMenu = new javax.swing.JMenu();
        Pedidosmen = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mesasMenu = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        cajaMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        cocinaMenu = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        insertarDatos = new javax.swing.JMenu();
        platosSubMenu = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        SubEmpleado = new javax.swing.JMenuItem();
        reporteMenu = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Koi Maki Bar");

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usu_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Cerrar Sesion");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 36));

        labUsuario.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        labUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/koi.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, 220));

        labNombre.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        labNombre.setForeground(new java.awt.Color(255, 255, 255));
        labNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 390, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BIENVENIDO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 280, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo nuevo.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 550, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pie.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 320, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pie.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 490, 140));

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 550);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        desktopPane.add(jPanel3);
        jPanel3.setBounds(0, 0, 710, 480);

        atencionMenu.setText("Atencion");

        Pedidosmen.setText("Pedidos");
        Pedidosmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosmenActionPerformed(evt);
            }
        });
        atencionMenu.add(Pedidosmen);

        jMenuItem1.setText("Registrar");
        atencionMenu.add(jMenuItem1);

        menuBar.add(atencionMenu);

        mesasMenu.setText("Mesas");

        jMenuItem5.setText("Estado");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mesasMenu.add(jMenuItem5);

        jMenuItem6.setText("Reservar");
        mesasMenu.add(jMenuItem6);

        menuBar.add(mesasMenu);

        cajaMenu.setMnemonic('f');
        cajaMenu.setText("Caja");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Registrar");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        cajaMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Consultar ");
        cajaMenu.add(saveMenuItem);

        menuBar.add(cajaMenu);

        cocinaMenu.setText("Cocina");

        jMenuItem7.setText("Consultar ");
        cocinaMenu.add(jMenuItem7);

        menuBar.add(cocinaMenu);

        insertarDatos.setText("Insertar datos");

        platosSubMenu.setText("Platos");
        platosSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platosSubMenuActionPerformed(evt);
            }
        });
        insertarDatos.add(platosSubMenu);

        jMenuItem8.setText("Mesas");
        insertarDatos.add(jMenuItem8);

        SubEmpleado.setText("Empleados");
        SubEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubEmpleadoActionPerformed(evt);
            }
        });
        insertarDatos.add(SubEmpleado);

        menuBar.add(insertarDatos);

        reporteMenu.setMnemonic('e');
        reporteMenu.setText("Reportes");

        jMenuItem10.setText("Reporte del día");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        reporteMenu.add(jMenuItem10);

        menuBar.add(reporteMenu);

        ayudaMenu.setMnemonic('h');
        ayudaMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerca de");
        ayudaMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Cerrar sesion");
        ayudaMenu.add(aboutMenuItem);

        menuBar.add(ayudaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void PedidosmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosmenActionPerformed
          if(evt.getSource()==platosSubMenu){
            if(me != null){
                desktopPane.remove(me);
            }
            me = new Menus();
            desktopPane.add(me);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = me.getSize();
            me.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            me.setVisible(true);

        }
        if(evt.getSource()==insertarDatos){

        }        
    }//GEN-LAST:event_PedidosmenActionPerformed

    private void platosSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platosSubMenuActionPerformed
        if(evt.getSource()==platosSubMenu){
            if(me != null){
                desktopPane.remove(me);
            }
            me = new Menus();
            desktopPane.add(me);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = me.getSize();
            me.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            me.setVisible(true);

        }
        if(evt.getSource()==insertarDatos){

        }
    }//GEN-LAST:event_platosSubMenuActionPerformed

    private void SubEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubEmpleadoActionPerformed

      
    }//GEN-LAST:event_SubEmpleadoActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Pedidosmen;
    private javax.swing.JMenuItem SubEmpleado;
    private javax.swing.JMenuItem aboutMenuItem;
    public static javax.swing.JMenu atencionMenu;
    public static javax.swing.JMenu ayudaMenu;
    public static javax.swing.JMenu cajaMenu;
    public static javax.swing.JMenu cocinaMenu;
    private javax.swing.JMenuItem contentMenuItem;
    public static javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenu insertarDatos;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labNombre;
    private javax.swing.JLabel labUsuario;
    public static javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu mesasMenu;
    private javax.swing.JMenuItem openMenuItem;
    public static javax.swing.JMenuItem platosSubMenu;
    public static javax.swing.JMenu reporteMenu;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
